# Site settings
title: 'Loki'  # Your Title
tagline: '做有趣的事情'  # A brief tagline for your site
sidebar_image: /images/cover.jpg


# Build settings
encoding: UTF-8
markdown: kramdown
#markdown: redcarpet
highlighter: pygments
#highlighter: false
baseurl: # the subpath of your site, e.g. /blog/
kramdown:
  input:         GFM
  auto_ids:      true
  auto_id_prefix:'id-'